### ISSUE TITLE
Problem with Tilt and Pan with Foscam FI9828P

### ISSUE THREAD

**Issue by scavenrage** [Skinah/IpCamera#13]
I've just added my new cam Foscam FI9828P.
Installed the add-on and added the thing with paperUI.
Everything seem working except for tilt and pan that move the cam just for half the available movement.
Tried to change the dimmer in a number, to force numbers greater than 100 but it doesn't work also.
Also the Zoom doesn't work at all

Thanks!

**Comment by Skinah** [comment]
Can you test the camera in the ONVIF device manager program?
https://sourceforge.net/projects/onvifdm/
The binding only support what is called ABSOLUTE movement as ONVIF has three different move methods, some cameras have flakey support for one method but work fine with other types so it would be interesting to see if...
a. your camera has a firmware update
b. if another movement method works fine.
c. if the camera does or does not work in the ODM program.

**Comment by Skinah** [comment]
This thread is related
https://github.com/Skinah/IpCamera/issues/17
