### ISSUE TITLE
FOSCAM: Add support for special characters inside username and password

### ISSUE THREAD

**Issue by SBado** [Skinah/IpCamera#14]
As per documentation:
```
The cgi request string must be encode in url format. URL encode rule:
The following chars will not be encoded:
[A~Z] [a~z] [0~9] + @ * /
The other chars will be encoded into hex format.
For example:
https://xxxxxx.myfoscam.org:443/cgi-bin/CGIProxy.fcgi?usr=admin&pwd=&cmd=getIPInfo
will be encode to:
https://xxxxxx.myfoscam.org:443/cgi-bin/CGIProxy.fcgi?usr%3Dadmin%26pwd%3D%26cmd%3DgetIPInfo
```
I had a number sign (#) inside my FI9821P's password, but I had to remove it beacause it wasn't encoded properly (it should be encoded as %23, but it isn't).

**Comment by Skinah** [comment]
Thanks for reporting, since I dont own Foscam this is a low priority but it is good to have it recorded as an issue.

**Comment by Skinah** [comment]
@SBado
 I may be able to implement this now are you able to test it if I make a release with the change?

**Comment by Skinah** [comment]
Next build will have this ability and will wait for a user to complain it does not work. Feel free to reopen issue or post in it closed if you test. Thanks for reporting this.
