### ISSUE TITLE
Dahua Text Overlay 

### ISSUE THREAD

**Issue by kristo2301** [Skinah/IpCamera#16]
Nice to have such function :
/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=20.1°C

answer form Cam:
OK

**Comment by Skinah** [comment]
Very low priority for me, but would accept a PR for this as it would be nice to have. If your camera has ability to BASIC auth you can probably do this in openhab with the http binding. If it needs DIGEST then this binding will be the only way. Need to first check what other brands are able to do this same feature and then come out with best name and set of features that works for all brands, plus it needs to be working behind a NVR if possible before a PR would be accepted.
&channel=x probably is all is needed for that and x=0 for standalone.

**Comment by cd-tronic** [comment]
What do you all think of giving the ability to send any Kind of API access to the cam? 
Something like a "Dummy-Channel" that only does stupid access without handling any answers?
eg you set a item:
`String CAM1Textoverlay "Textoverlay" { channel="ipcamera:DAHUA:001:dummy" }`
and sitemap:
`Selection item=CAM1Textoverlay  label="Cam1 Text Overlay" mappings=[0="/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=text1", 1="/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=text2", 2="/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=text3"]`

this way it would be possible to do nearly everything the APIs can handle

**Comment by cd-tronic** [comment]
The Problem is that the latest DAHUA cams or firmwares don't support basic auth anymore.

I tried using http binding for changeing camera profiles (normal, day, night) and got stuck realizing this issue. At that Moment ipcamerabinding didn't support digest, too (if i remember right). I don't know if it would work to use both bindings. Ipcamera for authentification and http binding for API access. 

I'm absolutely with you to keep bindings simple but this is might be an endless story.

I did a quick and dirty implementation. This was my first try on openhab development. It took only a few minutes to implement an APIAccess channel and works like a charm. 
I don't want to do a pull request cause there might be some Problems when someone wants to change multiple settings. You might need to use multiple 'APIAccess' channels cause of item feedback (selection might get empty if changeing a second camera setting).

**Comment by cd-tronic** [comment]
Hi,

Yes DIGEST should be implemented in HTTP Binding. Maybe it's time to update that binding to OH2.x and implement DIGEST. Maybe i will have a look at it in the future. 

I'm working on doing the apiAccess as an extensible Channel with URL provided in config. I think this is the best way to do this. :)

**Comment by Skinah** [comment]
What do you mean by extensible?

I would do it as a string channel and not hard tie it to a config string. This way multiple rules can use the same channel to add multiple api calls and variables can be used.

I strongly prefer to encourage people to add the feature to the binding instead of doing this because.

1. Then all users can enjoy the feature without having to open an api.

2. You can implement a way to display the cameras current setting when openhab or the camera reboots.

Look forward to seeing what you come up with.

**Comment by cd-tronic** [comment]
Hi Skinah, 
 so this is how i did it:
```
Thing ipcamera:DAHUA:005 [IPADDRESS="192.168.1.x", PASSWORD="xxxx", USERNAME="admin", POLL_CAMERA_MS=2000]
{
    Type string : apiConfig "ConfigString" [paramName="VideoInMode[0].Config[0]"]  //Videoprofile
}
```
for Textoverlay this should work:
```
Type string : apiConfig "ConfigString" [paramName="VideoWidget[0].CustomTitle[1].Text"] 
```
In this way it should also be possible to get and parse the informations from the Camera.

apiConfig is the name cause it works with all API-instructions using "setConfig". As far as i saw all instructions use that. "/cgi-bin/configManager.cgi?action=setConfig&"
 
the Code Looks like this:
```
case "DAHUA":
  org.eclipse.smarthome.core.thing.Channel channel = this.getThing().getChannel(channelUID.getId());
 // TODO: Add check if channel has apiConfig channel attached
  if (channel != null) {
       Map<String, Object> map = channel.getConfiguration().getProperties();
      String mapstring = map.get("paramName").toString();
      if (mapstring != null) {
      String apiMsg = "/cgi-bin/configManager.cgi?action=setConfig&" + mapstring + "="+ command.toString();
      sendHttpGET(apiMsg);
      }
  }
```
As you can see I didn't know how to check if the channel is a "apiConfig" channel. There should be another switch case instead of TODO. Do you know how to check this?


I wasn't able to push the changes. Do i need special rights or something like that? I'm not that experienced on using GIT.

**Comment by Skinah** [comment]
This really should be in its own issue as it is a completely separate feature we are talking about...

I have a number of concerns so hopefully it is a case of me not being as an advanced programmer as yourself but they are....

1. I dont believe a config is the correct way to do it, it should be a channel as the framework uses channels to connect items to a thing. Configs should be 1 time change when setting up a thing, channels are for constantly changing data passed from items to things. I see this as a non standard way to work which is more prone to having bugs and issues in future versions of openhab. But I am a noob at binding development so I am happy to be corrected so I can learn.

2. Does your way work with using paperUI only? if the answer is no then did you know that next Openhab version 3 is most likely going to discontinue textual config, this is being talked about on the forum at the moment. I dont support adding dead end code to the binding.

3. How would a user trigger this from a rule?

4. I dont support the idea of parsing, only the 1 way sending of a get request with no return being given to the user. If you want this ability then....

A) develop/extend the HTTP binding. 
B) Properly implement the feature into the binding and do it fully so the user does not have to parse.
C) Create your own version of the binding that you have to support and explain to people how to use it for the next 10+ years.

Not only will it be hard to implement, it will be a nightmare to support users that have questions about it. A binding should handle all complex communication to and from a device and completely remove the user from having to learn how to parse and really even opening up an API in the first place. I support the idea of a 1 direction sending of a call that is simple to use, just not a monster that has to keep being feed.

5. The channel/config name should be as we discussed earlier. We do not know what other cameras may want this in future and the name should make sense at first glance to people who do not use the binding and see a users code posted on a forum. If you have to explain why the name is used, that should be a warning that it is probably the wrong name. The name you have changed to I find confusing as to its intent, it make me think it is for configuring the API and not a direct way to send an API call. Next week we may have a camera brand X come along that only uses digest and we want to re-use channels and code and we then have an issue. This is why I stated lets agree on the name before you start.

**Comment by Skinah** [comment]
Both features are now implemented as I was putting in another feature and it took very little time to throw these in at the same time. Github has the code already and will create a JAR after it passes stability testing here..

To use in your rules files just do this...

```

BabyCamTextOverlay.sendCommand('Cot')

BabyCamAPIAccess.sendCommand('/cgi-bin/configManager.cgi?action=setConfig&Lighting[0][0].Mode=Off')

```
Both work here but the text overlay needs testing to see what happens when spaces and other characters are used in the string.

**Comment by cd-tronic** [comment]
Hi Skinah,
sorry for my late reply. I had been Pretty busy this weekend.

No problem if you don't want do add a feature like this. Just to clarify cause you said something about 10years+ support. In my oppinion that is why i would add this feature. You don't know what changes at the API's the next years. And this would be a pretty simple way to add nearly all features und future features to the binding.

>1.  I dont believe a config is the correct way to do it, it should be a channel as the framework uses channels to connect items to a thing. Configs should be 1 time change when setting up a thing, channels are for constantly changing data passed from items to things. I see this as a non standard way to work which is more prone to having bugs and issues in future versions of openhab. But I am a noob at binding development so I am happy to be corrected so I can learn.
> 2. Does your way work with using paperUI only? if the answer is no then did you know that next Openhab version 3 is most likely going to discontinue textual config, this is being talked about on the forum at the moment. I dont support adding dead end code to the binding.
> 3. How would a user trigger this from a rule?

I think you pretty much misunderstood what i did. I don't want to change anything on the openHAB config. Of course this uses channels and it is possible to do the whole config in paperUI. It is the same way it works in the KNX-binding. With "apiConfig" I'm refering to DAHUA Camera config. 
![paperui1](https://user-images.githubusercontent.com/7304760/52202228-314aa580-286e-11e9-9a55-a5791fc2706c.PNG)

![paperui2](https://user-images.githubusercontent.com/7304760/52202248-3c9dd100-286e-11e9-8d5d-3bf956e0d821.PNG)


> Not only will it be hard to implement, it will be a nightmare to support users that have questions about it. A binding should handle all complex communication to and from a device and completely remove the user from having to learn how to parse and really even opening up an API in the first place. I support the idea of a 1 direction sending of a call that is simple to use, just not a monster that has to keep being feed.

Well for parsing. Anyway you will have to parse the answer if you use the get-functions of the DAHUA API. As far as i saw you can only ask for all settings regarding one configurationpart. 
E.g. if you want to get the Bitrate of the videoencoding and using this for Setting:
`http://<ip>/cgi-bin/configManager.cgi?action=setConfig&Encode[0].ExtraFormat[0].Video.BitRate=<paramValue>` 
what would be only "Encode[0].ExtraFormat[0].Video.BitRate" in my apiConfig Parameter
you need to request this getfunction:
`http://<ip>/cgi-bin/configManager.cgi?action=getConfig&name=Encode`
and then parse this down.
![dahua](https://user-images.githubusercontent.com/7304760/52203035-71128c80-2870-11e9-84ba-49703b1af850.PNG)
It's pretty simple to do in the backend. We only need to search for our parameter and can see the value of it.

I don't want to create a own version of the binding. This would be pretty confusing to everyone. But we also don't need to add this feature if you don't want to.

**Comment by kristo2301** [comment]
Hi Skinah, 
Thanks for implementation, i will make some test with strings and report if detected any issue 

BR
Kristo

**Comment by Skinah** [comment]
@kristo2301 
Build is now uploaded as it ran for >24 hours on my system here as I mentioned in my last post...

@cd-tronic 
Please don't post further info in this thread, open a new one with a good title on what it is discussing. I am happy to remove what I added to change it to what you have been working on if it is simple and has improvements/benefits. See the updated readme.md file for how to use the new channel for API Access. It took 20 minutes to add the feature whilst adding some others I was doing.

Kai has mentioned that rules should not be used to parse and do implementations that a binding should do and I totally agree. If you have the skills to parse the data in rules you have the skills and should be doing this to the binding so that ALL USERS BENEFIT and the binding grows. I have at least 10 other reasons for this stance but it boils down to these two main points. The HTTP binding should get the ability to do this so I also see it as a waste of time adding the ability to a binding for cameras only, when a similar amount of work would then see it benefit all devices and far more users. The HTTP binding has the ability to return data for you to parse and it has documentation and more than 1 person giving replies on how that binding works.

**Comment by Skinah** [comment]
I can confirm that for a space to work in a String for text overlay you need to replace the spaces with '%20' as I suspected as a space is a non valid character in a URL. If you give me a list of non working characters in a new issue thread we can implement an auto filter to replace them.

**Comment by kristo2301** [comment]
After quick checking text overlay s changing channel title not text overlay area

**Comment by Skinah** [comment]
What url works for you then? My camera uses the url I hardcoded in and works great.

I found an easy way for testing is to use PaperUI and just paste the text in and press the tick icon to send it to the camera with the apiAccess channel. I will reopen this issue until this is resolved...

```
/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=customtexthere
```

**Comment by kristo2301** [comment]
it's strange if i use this channel in browser is working correctly , but
when used from binding is changing channel title not text overlay zone

śr., 6 lut 2019 o 05:17 Skinah <notifications@github.com> napisał(a):

**Comment by kristo2301** [comment]
==> /var/log/openhab2/openhab.log <==
2019-02-06 08:41:00.278 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Text Overlay was sent this command :AGarageIn
2019-02-06 08:41:00.283 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera at IP:192.168.2.12:80,  **URL:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn**
2019-02-06 08:41:00.289 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - CommonCameraHandler created.... 7 channels tracked (some of these may be closed).
2019-02-06 08:41:00.299 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:5   GET:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.309 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - API Access was sent this command :/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111

==> /var/log/openhab2/events.log <==
2019-02-06 08:41:00.307 [nt.ItemStatePredictedEvent] - ACAMGarageIn_Api predicted to become /cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111

==> /var/log/openhab2/openhab.log <==
2019-02-06 08:41:00.313 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera at IP:192.168.2.10:80,  URL:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.321 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - CommonCameraHandler created.... 12 channels tracked (some of these may be closed).
2019-02-06 08:41:00.328 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:7   GET:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.358 [DEBUG] [ipcamera.internal.MyNettyAuthHandler] - 401: Mark as closing, the  channel:7   GET:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.361 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Resending using a fresh DIGEST         URL:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.364 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera at IP:192.168.2.10:80,  URL:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.369 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - CommonCameraHandler created.... 12 channels tracked (some of these may be closed).
2019-02-06 08:41:00.377 [DEBUG] [ipcamera.internal.MyNettyAuthHandler] - 401: Mark as closing, the  channel:5   GET:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.380 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Resending using a fresh DIGEST         URL:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.383 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:8   GET:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.383 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera at IP:192.168.2.12:80,  URL:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.387 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:7   URL:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.401 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - CommonCameraHandler created.... 7 channels tracked (some of these may be closed).
2019-02-06 08:41:00.415 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Have re-opened  the closed channel:6   GET:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.418 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:5   URL:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.453 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Channel marked as closing, channel:8   URL:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.457 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:8   URL:/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text=11111
2019-02-06 08:41:00.487 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Channel marked as closing, channel:6   URL:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn
2019-02-06 08:41:00.491 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:6   URL:/cgi-bin/configManager.cgi?action=setConfig&ChannelTitle[0].Name=AGarageIn

**Comment by kristo2301** [comment]
Direct access to API is working ok : 
ACAMGarageIn_Api.sendCommand("/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[1].Text="+Temperature_Garage.state.format("%.1f") + "%C2%B0C")

Special charters have to be coded acc to  https://www.w3schools.com/tags/ref_urlencode.asp
UTF-8 code

**Comment by Skinah** [comment]
Next build, not yet available till later this evening...

URL is now changed to this as it supports turning it on and off via this method. Also I have implemented a better filter to support special characters.

```
/cgi-bin/configManager.cgi?action=setConfig&VideoWidget[0].CustomTitle[0].EncodeBlend=true&VideoWidget[0].CustomTitle[0].Text=Foo
```

**Comment by kristo2301** [comment]
@cd-tronic , 

How you are able to see this + to add channel?

**Comment by cd-tronic** [comment]
@kristo2301 as far as i saw has @Skinah implemented it in a pretty basic way. This was my first attempt, too but I decided that it was better to get a bit deeper for integration. 

However skinah did it in another way. Thats why you won't be able to add multiple channels and need to fool around with rules to use and merge multiple channels with apiAccess.

**Comment by kristo2301** [comment]
@cd-tronic is working pretty well on current solution with rules.

**Comment by cd-tronic** [comment]
> is working pretty well on current solution with rules.

jep. it's not the easiest way for enduser but should work fine :)

**Comment by Skinah** [comment]
@kristo2301

I would recommend you limit the use of the API Access as it may get pulled from the binding if I deem it to be a security risk. If you want new features just open a ticket here just as you have done. 

The text overlay channel is implemented and it should handle special cases automatically making it easier to use and no need to write documentation on special cases and how to handle.. I will close this issue, feel free to open it again if a problem is with the feature.

**Comment by kristo2301** [comment]
@Matthew Skinner <matt@pcmus.com>

Thanks for implementation, Api channel is good to test some items for
future implementation

czw., 7 lut 2019 o 00:31 Skinah <notifications@github.com> napisał(a):

**Comment by kristo2301** [comment]
@Skinah 
After checking on another Dahua firmware i detected an issue with overlay  i think you are using CustomTitle[0] which is not visible in new firmware if you can change it in some update in future it will be nice

**Comment by Skinah** [comment]
Can you tell me if CustomTitle[1] works for all your cameras? Yes CustomTitle[0] is what I use as the API indicates this is valid and the first Title to use. The only way I can set text on my Amcrest via the cameras own control panel is to use the "channel title", otherwise I need to use the API to access the custom titles which all work here.

If you can reply that CustomTitle[1] works on all of your cameras I can make the change very easily.

**Comment by kristo2301** [comment]
After deeper checking it's looking that camera which is not accepting
CustomTitle[0] have older FW  nad only one line is working form API , i
send request to seller to send me same one

niedz., 17 mar 2019 o 01:38 Skinah <notifications@github.com> napisał(a):

**Comment by Skinah** [comment]
new build now uploading with requested change.
