### ISSUE TITLE
TP-Link NC250 is working as generic image and not working in binding.

### ISSUE THREAD

**Issue by fmalfatto** [Skinah/IpCamera#23]
I have a TP-link NC250 that is supported in my sitemap as generic image giving snapshot:
Image url="http://user:base64_pwd@192.168.1.81:8080/stream/snapshot.jpg" refresh=1000
and it works with no other definition

But if I try to use the IpCamera binding, it does not work:

items:
Image Cam_Garage { channel="ipcamera:HTTPONLY:001:image" }
things:
Thing ipcamera:HTTPONLY:001 [IPADDRESS="192.168.1.81", PASSWORD="passwd", USERNAME="user", SNAPSHOT_URL_OVERIDE="http://user:base64_pwd@192.168.1.81:8080/stream/snapshot.jpg", PORT=8080, POLL_CAMERA_MS=1000]
sitemap:
Image url="http://google.com/leaveLinkAsThis" item=Cam_Garage refresh=1000

Any suggestion? I would prefere ti manage it with the same binding I use for other webcams.
TY

**Comment by fmalfatto** [comment]
Here it is!
[openhab.log.gz](https://github.com/Skinah/IpCamera/files/2632611/openhab.log.gz)

**Comment by Skinah** [comment]
Ok here is what my two cameras send as headers when an image is requested:

2018-12-15 22:09:40.228 [DEBUG] [.o.b.i.handler.IpCameraHandler:465  ] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 200 OK
Content-Type: image/jpeg; charset="UTF-8"
Connection: close
Content-Length: 171420


Here is what your camera sends:

[DEBUG] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.0)
HTTP/1.0 200 OK
Server: Streamd,A42BB01112D7
Date: Fri, 30 Nov 2018 08:49:21 UTC
Content-Type: image/jpg
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 98806
Connection: keep-alive


So my guess is this is the cause:
Mine and all other cameras use this
Content-Type: image/jpeg
VS
Content-Type: image/jpg

Next build will allow both to work so please report if this fixes your issue.

**Comment by fmalfatto** [comment]
I'm very careful with  bindings because I stil do not understand the way they are managed in Openhab. Each time I try to install/unisnstall something, I loose all my bindings and definitions and I have to restart from scratch. IpCamera is no more shown in my PaperUi pages so I do not know how to upgrade it. I tried to download from github but I had a whole folder structure of sources ...  maybe it's better for me to wait for an official release!
TY anyway

**Comment by Skinah** [comment]
You can download the latest Jar file from here
http://www.pcmus.com/openhab/
then just drop it into your addons folder and replace the older one. No need to edit any text files if you are using Openhab 2.3 and newer.

Thanks for sending the log file through as even if you do not use it, the odds are another user with a similar camera will use the changes I made.

**Comment by fmalfatto** [comment]
It's working perfectly. Thank you very much!
