### ISSUE TITLE
PORT always 80

### ISSUE THREAD

**Issue by brootes** [Skinah/IpCamera#3]
I download "ipcamera24-04-2018-First build to work with foscam" zip and installed in addons. I was able to configure but the PORT parameter does not seem to override the default value of 80. The log files always show trying to connect to 80 when I have set PORT=88.

Thing ipcamera:FOSCAM:001[IPADDRESS="xxx.xxx.xxx.xxx", PORT=88, ONVIF_PORT=80, PASSWORD="password",  USERNAME="username", ONVIF_MEDIA_PROFILE=0]

**Comment by Skinah** [comment]
The builds have the date in the format dd-mm-yyyy so you are using an old build. Please use the latest build which todays one is 12-05-2018 and see if there is still an issue. Is something not working, is this only an issue for logs or is it causing another issue?

In the latest builds the defaults for foscam are 
PORT=88
ONVIF_PORT=888

I see you have the ONVIF_PORT=80 so this may be why the logs are still showing 80 when the camera is trying to connect. It first connects with ONVIF first and then switches over to normal HTTP. I checked the code and it all seems fine, but I did add some better text to the logging to make this clearer.

Let me know if you have issues with the latest build and if you do try ONVIF_PORT=888

**Comment by brootes** [comment]
I downloaded the latest code. I reset the camera to PORT=88 and ONVIF_PORT=888 and did not set the ports in the thing, just used the defaults. I can see in the logs the initial connection returning the media profiles then it errors with:
2018-05-12 15:38:26.545 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0009: Message send failed
2018-05-12 15:38:26.551 [ERROR] [ing.ipcamera.handler.IpCameraHandler] - com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: com.sun.xml.internal.messaging.saaj.SOAPExceptionImpl: Message send failed
==> /var/log/openhab2/events.log <==
2018-05-12 15:38:26.554 [hingStatusInfoChangedEvent] - 'ipcamera:FOSCAM:001' changed from OFFLINE (CONFIGURATION_PENDING): Making a new connection to the camera now. to OFFLINE (COMMUNICATION_ERROR): Camera gave a SOAP exception during initial connection attempt
Thanks for your help!!

**Comment by Skinah** [comment]
Thanks for reporting this as I had a re-think of how the connection is made. For a lot of cameras ONVIF is only used to the get the snapshot url and PTZ (most cameras dont have PTZ) so now the binding has the ability to specify the snapshot address it was silly to refuse to try and connect with HTTP if ONVIF failed.

Can you try the newer 13-05-2018 version please?

The only difference between 12-05-2018 and 13-05-2018 is the binding now no longer fails to connect if a minor SOAP error occurs or if ONVIF wont connect. If you enter in a manual snapshot url (new feature mentioned above) the camera should be able to connect and be used no matter where the ONVIF soap error occurs or if the wrong ONVIF port was entered.

**Comment by brootes** [comment]
We are making progress. I am able to connect to the camera. The paperui is showing an image and automatically refreshing. I can see the ItemStateChangedEvent for the camera image in the log. Neither Pan or Tilt work. I am seeing the following in the log after I get the Media Profiles back.
2018-05-13 09:35:47.262 [INFO ] [ing.ipcamera.handler.IpCameraHandler] - About to interrogate the camera to see if it supports PTZ.
2018-05-13 09:35:57.797 [ERROR] [l.internal.messaging.saaj.client.p2p] - SAAJ0009: Message send failed.
Another note, when I tried to do an unlink, I received a Error 405 method not found.

Let me know if you want me to close the original issue and open a new one or not.
Thanks

**Comment by Skinah** [comment]
Can you open a new issue after doing the following please?

1. See if PTZ works with the “onvif device manager” open source program. 

2. Enable debugging on the bindings log so you can see which part of the PTZ fails to work. It should tell you what range the camera can move in. Some cameras support absolute PTZ locations and others support relative values and it may be your camera only responds to one of these types of movement.

3. Check for a updated firmware for your camera.


As for the unlink error I’ll have to test this with the latest build, I did it with no errors in the 12-05-2018 build so I would be surprised if there was something that caused this in the recent changes I just made. What version of openhab are you using?
