### ISSUE TITLE
Support org.osgi.framework version 1.7.0

### ISSUE THREAD

**Issue by falmanna** [Skinah/IpCamera#30]
The latest build of the binding doesn't run on Concierge framework. The stable version 5.1.0 of `org.eclipse.concierge` OSGI framework provides `org.osgi.framework` version 1.7.0 only, but the current implementation of IpCamera requires `osgi.extender`, specifically, the `osgi.component` 1.4.0<=version<=2.0.0 which requires `org.osgi.framework` version = 1.8.2

Even the incubation version 6.0.0 of Concierge can only provides `org.osgi.framework` version 1.8.0

**Comment by Skinah** [comment]
I'm sorry but I do not understand, I know almost zero on OSGI. If this is important for the binding to continue working in Openhab do you mind explaining it further for me please?

**Comment by falmanna** [comment]
I think I won't explain OSGi better than [this article](https://www.openhab.org/docs/developer/osgi/osgi.html).

And regarding working with Openahb, I think yes it affects that because all other bindings in Openahb do work with Concierge framework. I am not sure about the specific details, but [this section](https://www.openhab.org/docs/developer/guidelines.html#d-language-levels-and-libraries) of the documentation do discuss some minimum requirements. I am not sure if it is the same.

I would have tried to do it myself, but the binding doesn't have the `MANIFEST.MF` in the source code. Maybe it is about the new bnd tool that Openhab migrated to. But I believe it should not be hard to reduce the dependency version in order to support Concierge framework.

**Comment by Skinah** [comment]
You will need to explain why I should care? It works on openhab, so why is this an issue for you? if you are using this on another platform which is not openhab it may help to explain the why behind your request. All openhab binding from now on will not use a manifest file as they use the new bnd build system.

**Comment by falmanna** [comment]
It is not a problem that I only have, it is about the correct minimum supported version. All Openhab bindings do support `org.osgi.framework` 1.7.0 , so I think you should support this with the right dependencies, and it might be a requirement to have this binding added to the official Openhab rep. 

Unfortunately I didn't work with bndtools before, so I can be much of a help. But I would suggest that you look onto other bindings and look for the differences.

**Comment by Skinah** [comment]
I’m closing this issue because you are avoiding the question as to why you have an issue when openhab works fine. You seem to be hiding your true motives. Don’t waste my time.

**Comment by falmanna** [comment]
I explained my point exactly, there is no motive behind this issue, and I am not wasting your time!
I am talking about the minimum **osgi** version supported in Openahb.

For example, all Openhab bindings can run on [this](https://github.com/eclipse/smarthome-packaging-sample) lightweight version of ESH except your binding. All I said is that you might want to figure out why, because it might be something that Openhab requires. 

I will personally look more into this, but it will take me sometime before getting used to bndtools.
