### ISSUE TITLE
Exception "Camera has closed the channel" and exception ??? after reboot

### ISSUE THREAD

**Issue by lainsan** [Skinah/IpCamera#35]
First and foremost: big thanks for creating the binding. I finally got it to work with my [Hikvision DS-2CD2T46G1-4I/SL](https://www.hikvision.com/de/Product/Detail/443713337178218/579328519312049).

Two exceptions are now occurring quite often in my frontail logs - every 10min or so it's an exception related to the "camera has closed the channel":
[exception_camera has closed the channel.txt](https://github.com/Skinah/IpCamera/files/3699529/exception_camera.has.closed.the.channel.txt)

And an exception after restart of openhab which i cannot attribute to an error:
[exception_uncaught.txt](https://github.com/Skinah/IpCamera/files/3699530/exception_uncaught.txt)

Can you direct me into the direction of what i'm doing wrong here?

**Comment by Skinah** [comment]
Can you enable TRACE level log output and see what is happening? The cameras replies are shown in trace mode so if it is the camera closing the channel it may have more info. Readme has info on how to turn trace on.

**Comment by lainsan** [comment]
> Can you enable TRACE level log output and see what is happening? The cameras replies are shown in trace mode so if it is the camera closing the channel it may have more info. Readme has info on how to turn trace on.

Just a brief report: yes, will do. Unfortunately i had some issues with my openhab installation which i just solved. Will now try to look into the TRACE and get back here. :-)

**Comment by lainsan** [comment]
So when activating TRACE, it didn't seem to occur again. The binding worked well in my setup. I deactivated TRACE and the exception related to the camera has closed the channel occured only once today at 2pm - while i now even have a second camera active. 

As it's not reoccuring for now i'd close the issue. If it's occuring again, i'll make more efforts to get a TRACE.
