### ISSUE TITLE
How to get more than one shown from the same cam

### ISSUE THREAD

**Issue by Adityakush** [Skinah/IpCamera#36]
Hi !
Thanks for the binding, it works like a charm. One thing I want to ask though. My OH setup is on Pi. The animated GIF feature seems promising but I am not sure if it would be light on Pi’s resources. Is there a way I can get more than one image shown from the same camera taken after a time delay of a second or so.
I use an esp cam using the example configuration similar to TTGO cam. There is another nodemcu board with PIR motion sensor. I have set rule to turn on “update image” switch on motion detection and then turn off update image.
Is there a way to get two or more images updated from same camera but taken at different consecutive instants?

**Comment by Adityakush** [comment]
I tried the GIF option but it was saved to the directory in /tmp/AICamera but the GIF was not shown on the openhab interface. Is there some way to access that through OH??

**Comment by Adityakush** [comment]
The jpg are stored in /tmp/AICamera. How to show more than one in the openhab at the same time?? Or maybe is it possible to add controls to see previous jpg images on openhab screen??

**Comment by Skinah** [comment]
Please post in the openhab community, github is for bugs and not support.

**Comment by Adityakush** [comment]
Okay thanks
