### ISSUE TITLE
Add option to store snapshot on every update image event.

### ISSUE THREAD

**Issue by Adityakush** [Skinah/IpCamera#37]
Can you please add option to store snapshot to memory whenever update Image occurs.
That way we can save images to an external flash drive. It would be a great NVR alternative(atleast good for motion detection)

**Comment by Skinah** [comment]
You possibly asked this on the Openhab forum. It is possible to do this with an openhab rule that watches for when the image item changes and then the rule stores the contents of the image item to a file. Someone posted code/rule on how they did it on the forum.
When I get some more time to work on this binding, I will be trying to get it into the main addons project before adding further features.

**Comment by Adityakush** [comment]
Thanks a lot. For the time being I have implemented the rule you suggested. Thanks again
