### ISSUE TITLE
Camera stops updating

### ISSUE THREAD

**Issue by lainsan** [Skinah/IpCamera#41]
Hi Matt, as usual: thanks for the outstanding job in updating this binding!

Here' an issue I am encountering currently - not being sure, whether it's binding or camera related.

**Setup**:
- openHAB 2.5.0-1 (Release Build)
- ipcamera-2019-12-17.zip
- two IP cameras:
   - HIKVISION DS-2CD2T46G1-4I/SL, Frontyard, CAM01, local IP 192.168.1.100
   - HIKVISION DS-2CD2T46G1-4I/SL, Frontyard, CAM02, local IP 192.168.1.101

**Problem**:
Binding works well (alarms, image channels, evertyhing) for some time, but then seems to be stopping to update at a certain point. There's no obvious message error in the logs (not even when using trace).
I'm noticing when images (e.g. in HABPANEL or in PaperUI>Control) stop updating and alarms no longer work.
When trying to trigger Gif creation (sendCommand(ON)) the corresponding switch get's stuck "ON" never returning to OFF again.
When accessing my camera directly through it's web interface, LiveView is working fine. When looking into my NVR (Synology), live view or continous recording, it's working fine as well.

**Things config**:
Thing ipcamera:HIKVISION:tCam01 "tCam01" @ "Entrance"
[
    IPADDRESS="192.168.1.100",
    PASSWORD="(removed)",
    USERNAME="(removed)",
    POLL_CAMERA_MS=2000,
    SERVER_PORT=54324,
    ONVIF_PORT=9999,
    IP_WHITELIST="DISABLE",
    IMAGE_UPDATE_EVENTS=1,
    UPDATE_IMAGE=true,
    GIF_PREROLL=3,
    GIF_POSTROLL=18,
    FFMPEG_INPUT="rtsp://192.168.1.100:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1",
    FFMPEG_OUTPUT="/tmpfs/cam01/"
    ]

Thing ipcamera:HIKVISION:tCam02 "tCam02" @ "Garden"
[
    IPADDRESS="192.168.1.101",
    PASSWORD="(removed)",
    USERNAME="(removed)",
    POLL_CAMERA_MS=2000,
    SERVER_PORT=54325,
    ONVIF_PORT=9999,
    IP_WHITELIST="DISABLE",
    IMAGE_UPDATE_EVENTS=1,
    UPDATE_IMAGE=true,
    GIF_PREROLL=3,
    GIF_POSTROLL=18,
    FFMPEG_INPUT="rtsp://192.168.1.101:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1",
    FFMPEG_OUTPUT="/tmpfs/cam02/"
    ]

**Example**:
Today CAM01 (192.168.1.100) got stuck at 21.12.2019 16:14:01 - here's the last image i received incl timestamp attached:

![lastimage_cam01_12-21-2019_16-14-01](https://user-images.githubusercontent.com/56224339/71310371-adf95a80-2413-11ea-8ed7-0743b74032bb.jpg)

I then also noted CAM02 (192.168.1.101) got stuck as well, at 21.12.2019 16:06:29.

I attached the OH2 log snippet with ipcamera in TRACE mode from 16:00 - 16:16. 

[openhab.zip](https://github.com/Skinah/IpCamera/files/3991556/openhab.zip)

Both cameras are stuck in the following loop:

2019-12-21 16:16:05.863 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 835, cap: 835/835, unwrapped: PooledUnsafeDirectByteBuf(ridx: 835, widx: 835, cap: 4096)), decoderResult: success)
2019-12-21 16:16:05.864 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:\<EventNotificationAlert version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"\>
\<ipAddress\>192.168.1.100\</ipAddress\>
\<portNo\>80\</portNo\>
\<protocol\>HTTP\</protocol\>
\<macAddress\>bc:ba:c2:2e:31:b9\</macAddress\>
\<channelID\>1\</channelID\>
\<dateTime\>2019-12-21T16:16:06+01:00\</dateTime\>
\<activePostCount\>0\</activePostCount\>
\<eventType\>videoloss\</eventType\>
\<eventState\>inactive\</eventState\>
\<eventDescription\>videoloss alarm\</eventDescription\>
\<channelName\>\</channelName\>
\<Extensions version="1.0" xmlns="urn:psialliance-org"\>
\<serialNumber xmlns="urn:selfextension:psiaext-ver10-xsd"\>DS-2CD2T46G1-4I/SL20190708AAWRD37607327\</serialNumber\>
\<eventPush xmlns="urn:selfextension:psiaext-ver10-xsd"\>DS-2CD2T46G1-4I/SL20190708AAWRD37607327,2019-12-21T16:16:06+01:00,0,1.0\</eventPush\>
\</Extensions\>
\</EventNotificationAlert\>
:
2019-12-21 16:16:07.010 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 83, cap: 83/83, unwrapped: PooledUnsafeDirectByteBuf(ridx: 83, widx: 83, cap: 1024)), decoderResult: success)
2019-12-21 16:16:07.011 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:--boundary
Content-Type: application/xml; charset="UTF-8"
Content-Length: 845

:
2019-12-21 16:16:07.017 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 512, cap: 512/512, unwrapped: PooledUnsafeDirectByteBuf(ridx: 512, widx: 512, cap: 512)), decoderResult: success)
2019-12-21 16:16:07.018 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:\<EventNotificationAlert version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema"\>
\<ipAddress\>192.168.1.101\</ipAddress\>
\<portNo\>80\</portNo\>
\<protocol\>HTTP\</protocol\>
\<macAddress\>bc:ba:c2:2e:31:b2\</macAddress\>
\<channelID\>1\</channelID\>
\<dateTime\>2019-12-21T16:16:07+01:00\</dateTime\>
\<activePostCount\>0\</activePostCount\>
\<eventType\>videoloss\</eventType\>
\<eventState\>inactive\</eventState\>
\<eventDescription\>videoloss alarm\</eventDescription\>
\<channelName\>\</channelName\>
\<Extensions version="1.0" xml:
2019-12-21 16:16:07.019 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 333, cap: 333/333, unwrapped: PooledUnsafeDirectByteBuf(ridx: 333, widx: 333, cap: 8192)), decoderResult: success)
2019-12-21 16:16:07.020 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:ns="urn:psialliance-org"\>
\<serialNumber xmlns="urn:selfextension:psiaext-ver10-xsd"\>DS-2CD2T46G1-4I/SL20190708AAWRD37607320\</serialNumber\>
\<eventPush xmlns="urn:selfextension:psiaext-ver10-xsd"\>IO&amp;&amp;DS-2CD2T46G1-4I/SL20190708AAWRD37607320,2019-12-21T16:16:07+01:00,1.0\</eventPush\>
\</Extensions\>
\</EventNotificationAlert\>
:
 
**Workaround**:
I can change the things configuration (e.g. number of postroll images), save the file and with that apparently force an initialization. I just did that, and it's working well again.

**Suggestion**:
I'm not sure, this is binding related. It might be my cameras. However, this state is easy to discover in rules in OH2. If there was a function to enforce this re-initialization (what is it doing? reconnect?) i could work around that problem. :-)

**Comment by lainsan** [comment]
I accidently found a common occurence in the log - by switching off TRACE.
My cameras just stopped updating - at the same time in the log occured:

`2019-12-21 17:25:35.967 [WARN ] [ing.ipcamera.handler.IpCameraHandler] - Can't find ch when removing handler 		URL:null
2019-12-21 17:56:51.300 [WARN ] [ing.ipcamera.handler.IpCameraHandler] - Can't find ch when removing handler 		URL:null`

**Comment by Skinah** [comment]
Does your log meantion OOME or anything about the heap being out of space? I highly recommend changing to using this in your things file..
UPDATE_IMAGE=false
Then follow the readme on how to get snapshots using the url. Readme also has examples.
I am pretty sure there is a memory leak in the Openhab framework when sending high data to an image channel. 

Unless this has only started in the latest build as I have not run it for more than a few days due to doing lots of restarts whilst I am testing the new changes in the binding.

I find mine works for weeks on end with 5 cameras updating every second.

**Comment by lainsan** [comment]
There's no OOME or reference to heap anywhere in the logs (i do check openhab.log and events.log, correct?).
This behaviour has occured before 2.5 already (but i only tested it with 2.4).

I have just experimented a bit:
- update image is now false
- i am manually triggering image update when alarm occurs

I just reached a state, where sendCommand(ON) to updateImageNow or updateGif does turn them on but does not produce any reaction in the binding (no "activity" in the logs).
Also no error in the logs, no snapshots being updated, updateGif not returning to OFF, nothing being written to the directory (and of course ffmpeg hence not being executed).

In case logs (reduced to the last minutes) are interesting - i have attached them:

[events_snippet2.log](https://github.com/Skinah/IpCamera/files/3992387/events_snippet2.log)
[openhab_snippet2.log](https://github.com/Skinah/IpCamera/files/3992388/openhab_snippet2.log)

The only thing i see in the log: for both cameras events are happily being checked every roughly every 10s (detecting <eventType>videoloss</eventType><eventState>inactive</eventState> repeatedly).

_And then ..._
I just refreshed my things model (e.g. changing postroll 20 > 19). Cameras reinitialize and everything is fine again. I can trigger Alarms, which will trigger the updateImageNow, followed by createGif, which beautifully creates snapshots as well as the GIF.

**Comment by lainsan** [comment]
For cameras that are **not** working any more, it seems as the following log entry no longer occurs:

2019-12-22 12:39:21.344 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera: GET: http://192.168.1.101/ISAPI/Streaming/channels/101/picture

**Comment by Skinah** [comment]
The logs do not show anything useful that would give a clue. I doubt it is the camera since you can get it working again by changing a config, but to rule it out update your cameras firmware if you do not have a Chinese camera that should not be updated...
This leaves Openhab or the binding to rule out. For now you are the only one reporting it so my gut feeling is this is the heap space running out and it is possible for nothing to go into the logs if the memory ran out and stopped it from creating the log entry. Does everything else work fine in Openhab when this occurs?

See this post on how to diagnose and fix....
https://community.openhab.org/t/extra-java-opts-xmx-settings-ie-grafana-crashes-openhab-2-4/63342/7

How often does this occur? Will it run for 24 hours? currently since moving to Openhab 2.5 I probably have not run the system for more than 2 days due to rebooting to change to new code I am needing to test.

**Comment by lainsan** [comment]
It does not run for 24h - strange behavior does occur within this timeframe. It’s usually not both cameras at once - but both after some time (maybe a few hours in between).
There‘s not much i have set up in OH that could work fine - some rules on TimeOfDay, Presence detection - all of these seem unaffected and continue working seamlessly.

There’s no OOM errors so far. I will try playing with xmx memory parameters to see, if this affects the behavior. Thanks for hinting in that direction.

**Comment by lainsan** [comment]
Checked for memory leaks - no hints. Memory parameters have been increased just to be on the safe side.

> For cameras that are **not** working any more, it seems as the following log entry no longer occurs:
> 
> 2019-12-22 12:39:21.344 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera: GET: http://192.168.1.101/ISAPI/Streaming/channels/101/picture

Do you think not seeing the GET command being sent to a camera being „stuck“ might be something to further investigate on?

**Comment by lainsan** [comment]
I have dug a bit deeper - around when cameras stop working i find an exception in the OH logs:

> 2019-12-26 12:12:47.358 [WARN ] [ing.ipcamera.handler.IpCameraHandler] - !!!! Camera has closed the channel 	URL:/ISAPI/Streaming/channels/101/picture Cause reported is: {}
> java.io.IOException: Connection reset by peer
> 	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_222]
> 	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_222]
> 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_222]
> 	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_222]
> 	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_222]
> 	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247) ~[bundleFile:4.1.42.Final]
> 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147) ~[bundleFile:4.1.42.Final]
> 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[bundleFile:4.1.42.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [bundleFile:4.1.42.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [bundleFile:4.1.42.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [bundleFile:4.1.42.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [bundleFile:4.1.42.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [bundleFile:4.1.42.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [bundleFile:4.1.42.Final]
> 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.42.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.42.Final]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
> 

However: this exception does only occur for some stuck moments.

There's no hint in SYSLOG (I'm using an RPI4 on openhabian) on Java Crashing or something.

I had a brief look at the ipCamera handler source to maybe better understand, why the GET requests stop occuring. While i'm not a java expert by any means:
If i understand correctly you are creating single threads (e.g. pollCamera) which just continue running in the background.
Is there any reason, why any of these threads could stop or be stopped? Should it restart automatically when it's gone? Or can I somehow restart it by some triggers? (like: reinitializing when changing the things file)

**Comment by lainsan** [comment]
I think I can see a pattern - the connection breaks, when there is a channel related event, like:

> 2019-12-26 17:35:01.392 [WARN ] [ing.ipcamera.handler.IpCameraHandler] - Can't find ch when removing handler 		URL:null

Or 

> 2019-12-26 12:12:47.358 [WARN ] [ing.ipcamera.handler.IpCameraHandler] - !!!! Camera has closed the channel URL:/ISAPI/Streaming/channels/101/picture Cause reported is: {} java.io.IOException: Connection reset by peer

It does not seem to recover from that - only manual re initialize of the thing seems to fix it.

**Comment by Skinah** [comment]
I found this in the logs and when I also read on the Openhab forum you are running the cameras at the same time with Synology Surveillance Station it makes sense why the cameras are complaining they are too busy....


2019-12-21 16:14:10.904 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera: GET: http://192.168.1.100/ISAPI/Streaming/channels/101/picture
2019-12-21 16:14:10.904 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 8192, cap: 8192/8192, unwrapped: PooledUnsafeDirectByteBuf(ridx: 24576, widx: 55096, cap: 65536)), decoderResult: success)
2019-12-21 16:14:10.908 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] -    Using the already open channel:6 	GET:/ISAPI/Streaming/channels/101/picture
2019-12-21 16:14:10.908 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 503 Service Unavailable
Date: Sat, 21 Dec 2019 16:14:02 GMT
Server: webserver
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Content-Length: 310
Connection: keep-alive
Keep-Alive: timeout=8, max=98
Content-Type: application/xml
2019-12-21 16:14:10.910 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 8192, cap: 8192/8192, unwrapped: PooledUnsafeDirectByteBuf(ridx: 32768, widx: 55096, cap: 65536)), decoderResult: success)
2019-12-21 16:14:10.911 [TRACE] [ipcamera.internal.MyNettyAuthHandler] - MyNettyAuthHandler is now setup for 	GET:/ISAPI/Streaming/channels/101/picture
2019-12-21 16:14:10.915 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - Sending camera: GET: http://192.168.1.100/ISAPI/Streaming/channels/101/picture
2019-12-21 16:14:10.914 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 310, cap: 310/310, unwrapped: PooledUnsafeDirectByteBuf(ridx: 604, widx: 604, cap: 1024)), decoderResult: success)
2019-12-21 16:14:10.915 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 8192, cap: 8192/8192, unwrapped: PooledUnsafeDirectByteBuf(ridx: 40960, widx: 55096, cap: 65536)), decoderResult: success)
2019-12-21 16:14:10.917 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - HTTP Result back from camera is 	:<?xml version="1.0" encoding="UTF-8"?>
<ResponseStatus version="2.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<requestURL>/ISAPI/Streaming/channels/101/picture</requestURL>
<statusCode>2</statusCode>
<statusString>Device Busy</statusString>
<subStatusCode>deviceBusy</subStatusCode>
</ResponseStatus>
:
2019-12-21 16:14:10.920 [TRACE] [ing.ipcamera.handler.IpCameraHandler] - DefaultHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 8192, cap: 8192/8192, unwrapped: PooledUnsafeDirectByteBuf(ridx: 49152, widx: 55096, cap: 65536)), decoderResult: success)
2019-12-21 16:14:10.918 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] -    Using the already open channel:6 	GET:/ISAPI/Streaming/channels/101/picture
2019-12-21 16:14:10.924 [DEBUG] [ing.ipcamera.handler.IpCameraHandler] - commonCameraHandler closed channel:6 	URL:/ISAPI/Streaming/channels/101/picture

**Comment by Skinah** [comment]
503 error code means this from the HIK api:

“Service Unavailable” – The HTTP Server is up, but the REST service is not available. Typically this is caused by too many client requests

**Comment by Skinah** [comment]
Netty library had this known issue which may be the cause, suggest you update the netty files to the latest version in your addons folder and see if that fixes it.

https://github.com/netty/netty/pull/9674

**Comment by lainsan** [comment]
Current indication: problem with local setup, not binding. Hence, closing and working on local analysis.
