### ISSUE TITLE
How to install? Where is the instruction?

### ISSUE THREAD

**Issue by Bagunda** [Skinah/IpCamera#46]
How to install? Where is the instruction?

**Comment by Skinah** [comment]
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771

**Comment by Bagunda** [comment]
> https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771

Thanx! Maybe add a section "installation" and write a link there?

**Comment by Skinah** [comment]
Added to readme, thanks for feedback and suggestions.
