### ISSUE TITLE
/ipcamera.jpg doesn't work

### ISSUE THREAD

**Issue by Bagunda** [Skinah/IpCamera#47]
http://192.168.4.201:50001/ipcamera.jpg doesn't work
But http://192.168.4.201:50001/ipcamera.mjpeg - work.

`log:set TRACE org.openhab.binding.ipcamera`: http://bagsus.ru/hlam/openhab_log_for_github.txt

![image](https://user-images.githubusercontent.com/16766521/73449021-47048500-4373-11ea-85e3-77c51beb4636.png)
![image](https://user-images.githubusercontent.com/16766521/73449192-abbfdf80-4373-11ea-90db-5fc35bdd50a7.png)

**Comment by Skinah** [comment]
Upgrade the firmware of your camera, look at the image URL that got reported.

**Comment by Bagunda** [comment]
Image to this address (http://192.168.3.51/snap.jpg?JpegCam=1 and http://192.168.3.53/snap.jpg?JpegCam=1) are worked.
But I write credentials when I goin to this addresses.

![image](https://user-images.githubusercontent.com/16766521/73489501-c027ca80-43bb-11ea-9bae-955cf42bfa2d.png)

**Comment by Bagunda** [comment]
@Skinah, look!
In PapperUI ImageURL are bad. This is error in binding?

**Comment by Skinah** [comment]
I believe it is a bug in your cameras onvif. Often manufacturers ship products before they are done and release a firmware fix so always important to upgrade firmware.

You can use the override to get it working but I would do firmware as it may not be the only change the camera needs.
