### ISSUE TITLE
FFMPEG command line argument as parameter

### ISSUE THREAD

**Issue by scooper540** [Skinah/IpCamera#52]
Hello,

Firstly thank you very much for your work on this plugin which is making my camera available on openhab and especially habpanel.
My habpanel is running on a PI with an official 7' display having limited screen resolution.
In order to have the video on this screen, I used your plugin with ipcamera.mjpg
This is working really nice but the image is too big for my display.

I was investigating a bit and to solve my issue, I have to :
- create a simple script on my openhab server containing the ffmpeg command line with my scale resolution matching my display (see below)
- adding a timeout of 60s
- modifying my iframe on openhab to refresh it every 65s.
- modifying the config item for FFMPEG Path to use my script

This is working perfectly but it's a workaround.

Is it possible that you modify Line 1220 on IpCameraHandler.java in order to replace the  "-qscale:v 5 -r 6 -update 1" by something we can define in the item configuration ?
Then anybody would be able for example to change the output resolution of the stream by adding "-s 740x370" with the original parameters.

Thank you very much for your work !

timeout 60 /usr/bin/ffmpeg -an -rtsp_transport tcp -i rtsp://192.168.100.90/user=admin_password=XXXXXXXXXXX_channel-1_stream=0.sdp -s 740x370 -qscale:v 1 -r 6 -update 1 http://127.0.0.1:54321/ipcamera.jpg

https://github.com/Skinah/IpCamera/blob/98e0606251cc55a5f23259b3b647331f215e2526/src/main/java/org/openhab/binding/ipcamera/handler/IpCameraHandler.java#L1220

**Comment by Skinah** [comment]
Next build will have this ability and it is advanced so if looking for it in paperUI you need to click on show more (?) I think the link is to see it. Called FFMPEG_MJPEG_ARGUMENTS
