### ISSUE TITLE
UPDATE_IMAGE Syntax

### ISSUE THREAD

**Issue by Protheus23** [Skinah/IpCamera#59]
Hi,

i installed my IP-Cams and your Binding.
It works great, but after a reboot, i have to set UpdateImageNow to get a Snapshot from the cams.

I think the UPDATE_IMAGE Agument is the correct one but its not working.
By the way i work with text-files and -definitions.

Thing ipcamera:HIKVISION:002 "CAM02-Hinten" @ "Cameras"
[
    IPADDRESS="<CAM-IP>",
    USERNAME="<OpenhabUser on Cam>",
    PASSWORD="<OpenhabUser-PW>",
    ONVIF_PORT=80, //normally 80 check what it needs
    PORT=80,
    NVR_CHANNEL=1,
    SERVER_PORT=8000,
    FFMPEG_OUTPUT="/media/openhab/Camera/Cam02-Hinten/",
->UPDATE_IMAGE="ON"  ?????
]

I tried     

UPDATE_IMAGE="ON"
UPDATE_IMAGE=ON
UPDATE_IMAGE="1"
UPDATE_IMAGE=1

but nothing works.
What is the correct syntax to archieve this?
I want to show the Cams every time (even after reboot) without to set the UpdateImageNow

Greets
Jens

**Comment by Skinah** [comment]
UPDATE_IMAGE=true
But it is not a good idea to use the Image channel, instead use the other features outlined in the readme.

**Comment by Protheus23** [comment]
> UPDATE_IMAGE=true
> But it is not a good idea to use the Image channel, instead use the other features outlined in the readme. There is also a newer build and I may have fixed an issue or two for the image channel in the last few days.

Hi Skinah,

thanks for fast reply.
What do you mean? Is there a possibility to show a direct stream from the Cameras (Or even better my QNAP Surveilance Station)?

Greets
Jens

**Comment by Skinah** [comment]
Yes and the readme goes into detail.
