### ISSUE TITLE
[EZViz DB-1] ONVIF /CellMotionDetector/Motion (PIR) shows up on wrong channel

### ISSUE THREAD

**Issue by bgilmer77** [Skinah/IpCamera#60]
Hardware: EZViz DB-1 running HikVision FW
Setup: Tape applied over camera lense.  PIR sensor exposed.  Moved hand in front of PIR sensor until 'beep' heard from DB-1 speaker.

Problem description: PIR motion alarms seem to show up on the ipcamera:ONVIF:doorbell:motionAlarm channel.  I believe they should show up on the ipcamera:ONVIF:doorbell:pirAlarm channel.

.things file
```
Thing ipcamera:ONVIF:doorbell
[
        IPADDRESS="192.168.18.30",
        USERNAME="admin",
        PASSWORD="JEGRAK",
        POLL_CAMERA_MS=2000000,
        SNAPSHOT_URL_OVERRIDE="http://192.168.18.30/onvif/snapshot.jpg",
        SERVER_PORT=54030,
        FFMPEG_INPUT="rtsp://192.168.18.30:554/Streaming/Channels/101",
        FFMPEG_OUTPUT="/tmpfs/doorbell/"
]  
```

.items file
```
Switch doorbellPIR "doorbell PIR" { channel="ipcamera:ONVIF:doorbell:pirAlarm" }
Switch doorbellMotion "doorbell Motion" { channel="ipcamera:ONVIF:doorbell:motionAlarm" }
```

From openhab.log
```
2020-07-14 16:54:34.134 [DEBUG] [nding.ipcamera.onvif.OnvifConnection] - Onvif Event Topic:RuleEngine/CellMotionDetector/Motion, Data:IsMotion, Value:true
```

From events.log
```
2020-07-14 16:54:36.059 [vent.ItemStateChangedEvent] - doorbellMotion changed from ON to OFF
```

**Comment by Skinah** [comment]
Heads up the password is showing in the things file you posted.

 CelMotionDetector is not set aside for PIR and many cameras with no PIR use this for their normal detection. It is explained in less nerdy talk here and the picture helps explain the cell part...
https://altaroca.wordpress.com/2014/07/20/onvif-analytics/

I could not get any motion reported when I covered up the cameras lens. Can you confirm it was not a shaddow going through your tape? be sure to 100% block the lens out. Can you get one of the events to get reported without the other one or do they both always turn to true like they are linked internally in the camera? Use the DEBUG logs to watch the raw events getting reported and ignore the controls in Openhab when doing this testing...

**Comment by Skinah** [comment]
I'll close this issue and if all discussion can be done in the one single thread, over here...

https://github.com/Skinah/IpCamera/issues/61
