### ISSUE TITLE
[EZViz DB-1] ONVIF /VideoSource/MotionAlarm does not appear to trigger motionAlarm channel

### ISSUE THREAD

**Issue by bgilmer77** [Skinah/IpCamera#61]
Hardware: EZViz DB-1 running HikVision FW

Setup: Tape applied over PIR sensor. Moved hand in front of camera lense.  Never heard a beep from DB-1 speaker (normal - beep appears to only trigger for PIR motion alarms).

Problem description: Motion detection in camera video seems to be working, as indicated by ONVIF in openhab.log, but the associated channel does not seem to change state.  Specifically, Onvif Event Topic VideoSource/MotionAlarm changes state to `true`, but channel `ipcamera:ONVIF:doorbell:motionAlarm` does not change state.  (Maybe this is because PIR motion alarms are showing up on this channel instead?  See #60 .

.things file
```
Thing ipcamera:ONVIF:doorbell
[
        IPADDRESS="192.168.18.30",
        USERNAME="[username]",
        PASSWORD="[password]",
        POLL_CAMERA_MS=2000000,
        SNAPSHOT_URL_OVERRIDE="http://192.168.18.30/onvif/snapshot.jpg",
        SERVER_PORT=54030,
        FFMPEG_INPUT="rtsp://192.168.18.30:554/Streaming/Channels/101",
        FFMPEG_OUTPUT="/tmpfs/doorbell/"
]  
```

.items file
```
Switch doorbellPIR "doorbell PIR" { channel="ipcamera:ONVIF:doorbell:pirAlarm" }
Switch doorbellMotion "doorbell Motion" { channel="ipcamera:ONVIF:doorbell:motionAlarm" }
```

openhab.log file
```
2020-07-14 17:09:08.023 [DEBUG] [nding.ipcamera.onvif.OnvifConnection] - Onvif Event Topic:VideoSource/MotionAlarm, Data:State, Value:true
```

events.log file
```
2020-07-14 17:09:09.034 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:09.101 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:10.012 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:10.083 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:11.000 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:11.062 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:11.993 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:12.061 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:12.990 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
2020-07-14 17:09:13.064 [thome.event.ItemStateEvent] - doorbellMotion updated to OFF
```

**Comment by Skinah** [comment]
Both should be triggering the same alarm channel. This is a sample of the code used which should show both get handled the same way deliberately. If you find one does not move the alarm, then check for any extra/missing or different characters as it must be an exact match...

```java
case "RuleEngine/CellMotionDetector/Motion":
            case "VideoSource/MotionAlarm":
                if (dataValue.equals("true")) {
                    ipCameraHandler.motionDetected(CHANNEL_MOTION_ALARM);
                } else if (dataValue.equals("false")) {
                    ipCameraHandler.noMotionDetected(CHANNEL_MOTION_ALARM);
                }
                break;
```

**Comment by Skinah** [comment]
BTW edit your password out of your post.

**Comment by bgilmer77** [comment]
How about if we discuss this over on community.oh?  That way if others have the same question, they can find the answer in that thread.

**Comment by Skinah** [comment]
The problem with that thread is that in only 2 days you cant find anything in there as it is too big and not focused on only 1 topic.

How does this sound...

``VideoSource/MotionAlarm`` this goes to a channel called ``motionAlarm``

``RuleEngine/CellMotionDetector/Motion`` this goes to a channel called ``cellMotionAlarm``

Does that make sense and logical? Any other ideas? We need to think of all the other cameras which use these two topics as I am pretty sure neither of these two are set aside for PIR sensors, so IMHO it is silly to send it to a channel called anything related to PIR as people will not know that is where the event ends up.

**Comment by bgilmer77** [comment]
I agree that these two mappings are a good solution.  I also agree that abandoning PIR makes sense if that same ONVIF topic is used in different ways by other cameras.  I don't know about Australian, but in American, it does take a little bit of translating to get from 'cell' to 'PIR sensor', but it is not too much of a stretch.

**Comment by Skinah** [comment]
I see this is going to be a commonly asked question, so having this in its own issue here allows me to now direct people here to see the 'back story' of why it was done. I suspect that most cameras on the market use RuleEngine/CellMotionDetector/Motion for their main motion alarm notifications, so sadly the bulk of people are going to have trouble working out why the motionAlarm channel does not move for them.

I don't see any other way forward that allows separate access to both topics without creating a confusing situation.

The change has been made and will be in the next build so closing this issue.

**Comment by bgilmer77** [comment]
Just for clarification, I am not sure about your final decision regarding addressing this issue.  Did you decide to implement this?
`VideoSource/MotionAlarm` this goes to a channel called `motionAlarm`

`RuleEngine/CellMotionDetector/Motion` this goes to a channel called `cellMotionAlarm`
