### ISSUE TITLE
[HikVision DS-HD1] Audio capture to .mp4 not working

### ISSUE THREAD

**Issue by bgilmer77** [Skinah/IpCamera#62]
As reported on [the OpenHAB Community](https://community.openhab.org/t/working-doorbell-hikvision-ds-hd1/102487/49), audio recording from the HikVision DS-HD1 to a .mp4 file appears not to work.

**Comment by Skinah** [comment]
The next build of the binding will have a new config called ``FFMPEG_MP4_OUT_ARGUMENTS`` and you can see it if you click show more in PaperUI as it is an advanced config. The default will now copy the audio and video to the mp4 file, plus you will be able to do all kinds of cool things like even out loud and soft audio by doing things like this blog goes into...

https://medium.com/@jud.dagnall/dynamic-range-compression-for-audio-with-ffmpeg-and-compand-621fe2b1a892

If you get the compand audio filter working, please post what the syntax is as I don't have the time to play with it.
