### ISSUE TITLE
Escam http commands, need help testing.

### ISSUE THREAD

**Issue by Skinah** [Skinah/IpCamera#8]
Can someone with an Escam camera try these in any browser and confirm that they all work please?

Motion ON

```
http://IP:PORT/set_alarm.cgi?loginuse=user&loginpas=pass&motion_armed=1&motion_sensitivity=6&presetsit=0
```

Motion OFF

```
http://IP:PORT/set_alarm.cgi?loginuse=user&loginpas=pass&motion_armed=0
```

Check if Motion is on or off

```
http://IP:PORT/get_params.cgi?loginuse=user&loginpas=pass
```

returns 1 or 0 in this string.

```
alarm_motion_armed=
```

Check Alarm

```
http://IP:PORT/get_status.cgi?loginuse=user&loginpas=pass
```

returns this with 1 or 0

```
alarm_status=
```

**Comment by fapgomes** [comment]
Hi,

 Unfortunately, doesn't work:

wget -q "http://192.168.1.106/get_status.cgi?loginuse=admin&loginpas=pass" -O -
<html><head><title>404 File Not Found</title></head>
<body>The requested URL was not found on this server</body></html>

Best Regards,
Fernando Gomes
